# Generated by Django 3.1.7 on 2021-03-10 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libraryapp', '0002_article_biography_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='наименование проекта')),
                ('repository_url', models.URLField(verbose_name='url репозитория проекта')),
                ('users', models.ManyToManyField(to='libraryapp.Author', verbose_name='участники проекта')),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('is_active', models.BooleanField(default='признак активации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todoapp.project', verbose_name='проект')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='libraryapp.author', verbose_name='пользователь')),
            ],
        ),
    ]
