# Generated by Django 3.1.7 on 2021-03-11 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='users',
            new_name='authors',
        ),
    ]
