# Generated by Django 3.1.7 on 2021-03-15 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20210315_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapp',
            name='access_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 16, 30, 29, 296834, tzinfo=utc), verbose_name='срок действия токена доступа'),
        ),
        migrations.AlterField(
            model_name='userapp',
            name='refresh_token_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 17, 16, 30, 29, 296882, tzinfo=utc), verbose_name='срок действия токена обновления'),
        ),
    ]
