default:
  SECRET_KEY: ""
  DEBUG: true
  ALLOWED_HOSTS: ""
  WSGI_APPLICATION: ""

development:
  DEBUG: true
  ALLOWED_HOSTS:
    - "127.0.0.1"
    - "localhost"
  WSGI_APPLICATION: "settings.wsgi.application"
