# Generated by Django 3.1.7 on 2021-03-15 16:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ид')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('birthday_year', models.PositiveIntegerField(verbose_name='год рождения')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.userapp', verbose_name='пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ид')),
                ('name', models.CharField(max_length=128, verbose_name='наименование книги')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryapp.author', verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ид')),
                ('text', models.TextField(verbose_name='биография')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryapp.author', verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование статьи')),
                ('text', models.TextField(verbose_name='текст статьи')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryapp.author', verbose_name='автор')),
            ],
        ),
    ]
