# Generated by Django 3.1.7 on 2021-03-10 17:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biography',
            fields=[
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='libraryapp.author', verbose_name='автор')),
                ('text', models.TextField(verbose_name='биография')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ид')),
                ('name', models.CharField(max_length=128, verbose_name='наименование книги')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryapp.author', verbose_name='автор')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='наименование статьи')),
                ('author', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryapp.author', verbose_name='автор')),
            ],
        ),
    ]
