# Generated by Django 3.1.7 on 2021-03-11 14:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20210311_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='biography',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='ид'),
        ),
        migrations.AlterField(
            model_name='biography',
            name='author',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='libraryapp.author', verbose_name='автор'),
        ),
    ]
