# Generated by Django 3.1.7 on 2021-03-16 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_auto_20210316_1247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='author_uuid',
        ),
        migrations.RenameField(
            model_name='biography',
            old_name='author',
            new_name='author_uuid',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='author',
            new_name='author_uuid',
        ),
    ]
