# Generated by Django 3.1.7 on 2021-03-20 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0005_auto_20210316_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author_uuid',
            new_name='author',
        ),
    ]
